### ISSUE TITLE
After adding AddSessionStateTempDataProvider to my MVC configuration I get an InvalidOperationException

### ISSUE THREAD

**Issue by Franklin89** [nabinked/NToastNotify#50]
After adding `.AddSessionStateTempDataProvider()` to my MVC configuration I get the following exception: 
```
InvalidOperationException: Session has not been configured for this application or request.
Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
Microsoft.AspNetCore.Mvc.ViewFeatures.SessionStateTempDataProvider.LoadTempData(HttpContext context)
Microsoft.AspNetCore.Mvc.ViewFeatures.TempDataDictionary.Load()
Microsoft.AspNetCore.Mvc.ViewFeatures.TempDataDictionary.ContainsKey(string key)
NToastNotify.TempDataWrapper.Peek<T>(string key)
NToastNotify.MessageContainers.TempDataMessageContainer<TMessage>.GetAll()
NToastNotify.MessageContainers.TempDataMessageContainer<TMessage>.ReadAll()
NToastNotify.ToastNotification<TMessage, TOptions>.ReadAllMessages()
NToastNotify.NToastNotifyViewComponent.Invoke()
lambda_method(Closure , object , object[] )
Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(object target, object[] parameters)
Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeSyncCore(ObjectMethodExecutor executor, ViewComponentContext context)
Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
StackExchange.Profiling.Internal.ProfilingViewComponentInvoker.InvokeAsync(ViewComponentContext context) in ProfilingViewComponentInvoker.cs
Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeCoreAsync(ViewComponentDescriptor descriptor, object arguments)
AspNetCore.Views_Shared__Layout+<>c__DisplayClass53_0+<<ExecuteAsync>b__1>d.MoveNext() in _Layout.cshtml
+
    @await Component.InvokeAsync("NToastNotify")
```

I did configure the session (`sevices.AddSession()` and  `app.UseSesssion()`), so not sure why this exception occurs.

`app.UseSession` is called before `app.UseMvc` and also before `app.UseNToastNotify`

**Comment by nabinked** [comment]
Were you able to fix this ? Sorry for not getting back earlier.

**Comment by ferryferry** [comment]
I have the same problem as @Franklin89 

`System.InvalidOperationException: Session has not been configured for this application or request.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
   at Microsoft.AspNetCore.Mvc.ViewFeatures.SessionStateTempDataProvider.LoadTempData(HttpContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.TempDataDictionary.Load()
   at Microsoft.AspNetCore.Mvc.ViewFeatures.TempDataDictionary.ContainsKey(String key)
   at NToastNotify.TempDataWrapper.Get[T](String key)
   at NToastNotify.MessageContainers.TempDataMessageContainer`1.Add(TMessage message)
   at NToastNotify.ToastNotification`2.AddMessage(TMessage toastMessage)
   at NToastNotify.ToastrNotification.AddErrorToastMessage(String message, ILibraryOptions toastrOptions)
   at JSpend.WebApplication.Controllers.HomeController.LoginNotAuthorized() in C:\Users\Jongmans\Source\Repos\NIC-JSpend\6 WebApplication\JSpend.WebApplication\Controllers\HomeController.cs:line 33
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at NToastNotify.NtoastNotifyAjaxToastsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

And the controllermethod looks like this: (which is not authorized at all)

`		public IActionResult LoginNotAuthorized()
		{
            _toastNotification.AddErrorToastMessage(_sharedLocalizer.GetString("You are not allowed to log in for this application"));
			return View("Index");
		}`

**Comment by ferryferry** [comment]
@Franklin89 Have you fixed it yet?

**Comment by nabinked** [comment]
Sorry guys unable to reproduce this. The following startup code works just fine. 
```
public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().AddFeatureFolders().AddNToastNotifyNoty(
                new NotyOptions
                {
                    ProgressBar = true,
                    Timeout = 5000,
                    Theme = "metroui",
                }).AddSessionStateTempDataProvider();
            services.AddSession();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseBrowserLink();
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseStaticFiles();
            app.UseSession();

            app.UseNToastNotify(); // This must be above the UseMvc() line
            app.UseMvcWithDefaultRoute();

        }
    }
```

**Comment by Franklin89** [comment]
You are using the `Noty`. Until now I have only tested using `Toastr`. The error does not happen on the initial call to the Index page. Refresh by hitting F5 and the error will happen.

```cs
public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.AddSession();

            services.AddMvc()
                .AddSessionStateTempDataProvider()
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_1)
                .AddNToastNotifyToastr();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseStaticFiles();
            app.UseCookiePolicy();

            app.UseSession();
            app.UseNToastNotify();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }
```

```
public IActionResult Index()
        {
            _toastNotification.AddInfoToastMessage("Hello World");
            return View();
        }
```

**Comment by nabinked** [comment]
Closing due to inactivity

**Comment by paddy16224** [comment]
please reopen this issue as i am facing same error in my project.

**Comment by paddy16224** [comment]
using similar code from your samples.
like NToastNotify-master\sample\NToastNotify.Toastr\Controllers\HomeController.
when the index method is hit for first time all the messages are shown.
tried to refresh or reload the home page. then while adding first message in toastr it throws the same session error.

Error is thrown from below specific line:
at NToastNotify.TempDataWrapper.Get[T](String key)

stack trace for your reference :
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
   at Microsoft.AspNetCore.Mvc.ViewFeatures.SessionStateTempDataProvider.LoadTempData(HttpContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.TempDataDictionary.Load()
   at Microsoft.AspNetCore.Mvc.ViewFeatures.TempDataDictionary.ContainsKey(String key)
   at NToastNotify.TempDataWrapper.Get[T](String key)
   at NToastNotify.MessageContainers.TempDataMessageContainer`1.Add(TMessage message)
   at ATS.ERP.SimplyYou.Controllers.HomeController.Index() in C:\Toster\ERP\ERP.SimplyYou\Controllers\HomeController.cs:line 28
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()

**Comment by paddy16224** [comment]
my startup.cs is as below 

public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => false;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            // The Tempdata provider cookie is not essential. Make it essential
            // so Tempdata is functional when tracking is disabled.
            services.Configure<CookieTempDataProviderOptions>(options => {
                options.Cookie.IsEssential = true;
            });

            //services.Configure<IISOptions>(options => { });
            services.AddDbContextPool<ERPContext>(options => options.UseSqlServer(Configuration.GetConnectionString("ERPContext")));

            services.AddIdentity<ApplicationUser, IdentityRole<long>>(option =>
            {
                option.User.RequireUniqueEmail = true;
                option.SignIn.RequireConfirmedEmail = true;

                //User LockOut Settings 
                option.Lockout.AllowedForNewUsers = true;
                option.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(5);
                option.Lockout.MaxFailedAccessAttempts = 3;

                //Password Setting
                option.Password.RequireDigit = true;
                option.Password.RequiredLength = 8;
                option.Password.RequiredUniqueChars = 1;
                option.Password.RequireLowercase = true;
                option.Password.RequireNonAlphanumeric = true;
                option.Password.RequireUppercase = true;
            })
                .AddEntityFrameworkStores<ERPContext>()
                .AddDefaultTokenProviders();

            //Add for Mail Confirmation And ForgotPassword
            services.Configure<AuthMessageSenderOptions>(Configuration);

            // Add our Config object so it can be injected
            services.Configure<ApplicationSettings>(Configuration.GetSection("ApplicationSettings"));

            //services.AddAutoMapper();

            services.AddSession();

            services.AddMvc()
                .AddSessionStateTempDataProvider()
                .AddNToastNotifyToastr();
        }

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
            .SetBasePath(env.ContentRootPath)
            .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
            .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
            .AddEnvironmentVariables();

            Configuration = builder.Build();

            if (env.IsDevelopment() || env.EnvironmentName == "Local")
            {
                //_logger.LogInformation("In Development environment");
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();
            }
            else
            {
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseStaticFiles();
            //app.UseAuthentication();
            app.UseCookiePolicy();
            app.UseSession();

            app.UseNToastNotify(); // This must be above the UseMvc() line

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");

                routes.MapRoute(
                   name: "areas",
                   template: "{area:exists}/{controller=PaymentTypeWise}/{action=Index}/{id?}"
                 );

            });
        }

**Comment by nabinked** [comment]
Thanks for the details. Reopening this. Will investigate soon when I get time. Meanwhile a PR is always welcome if you can identify the issue.

**Comment by nabinked** [comment]
Revisited this and tried reproducing and cannot do. Check the Toastr Sample. I have pushed in a separate branch https://github.com/nabinked/NToastNotify/compare/test-session-temp-data-provider.

**Comment by nabinked** [comment]
Closing this due to lack of response.
