### ISSUE TITLE
Error on IIS deployment

### ISSUE THREAD

**Issue by ToluAgabi** [nabinked/NToastNotify#91]
Everything works locally but i get this error on deployment to IIS

`System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.TempDataDictionary.set_Item(String key, Object value)
   at NToastNotify.TempDataWrapper.Add(String key, Object value)
   at NToastNotify.MessageContainers.TempDataMessageContainer`1.Add(TMessage message)
   at NToastNotify.ToastNotification`2.AddMessage(TMessage toastMessage)
   at NToastNotify.ToastrNotification.AddSuccessToastMessage(String message, ILibraryOptions toastrOptions)
   at FidelityAPIMdelegate.Controllers.AdminController.CreateProduct(TempProduct product) in C:\Users\Tolulope Agabielesin\source\repos\fidelitybillingportal\FidelityAPIMdelegate\Controllers\AdminController.cs:line 1201
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at NToastNotify.NtoastNotifyAjaxToastsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)`

**Comment by nabinked** [comment]
Steps to reporduce please ?

**Comment by ToluAgabi** [comment]
upgrading package solved it

**Comment by ToluAgabi** [comment]
When an action is performed for a user, toast shows for other users

**Comment by nabinked** [comment]
Can you explain more ?

**Comment by nabinked** [comment]
> When an action is performed for a user, toast shows for other users

Please create a new issue for this one if its still a problem. Closing this.
